name: Web3Pay CI

on:
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
name: Web3Pay CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build project (optional)
        run: npm run build

      - name: Upload test results (optional)
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/

      - name: Notify on failure
        if: failure()
        run: echo "โ Workflow failed. Check logs for details."
# Web3Pay CI Workflow

ูุฐุง ุงูุชูููู ููุฏู ุฅูู ุถูุงู ุฌูุฏุฉ ุงูููุฏ ูุงุณุชูุฑุงุฑู ูู ูุดุฑูุน Web3Payุ ุนุจุฑ ุชูููุฐ ุณูุณูุฉ ูู ุงููุญูุตุงุช ุงูุชููุงุฆูุฉ ุนูุฏ ูู ุชุนุฏูู ุนูู ูุฑุน `main`.
## ๐ Trigger

ูุชู ุชุดุบูู ูุฐุง ุงูุชูููู ุชููุงุฆููุง ุนูุฏ:

- ุฃู ุนูููุฉ `push` ุฅูู ูุฑุน `main`
- ุฃู `pull request` ููุฌู ุฅูู ูุฑุน `main`

> ุงููุฏู ูู ูุฐุง ุงูุชูุนูู ูู ุถูุงู ุฃู ูู ุชุนุฏูู ูุชู ูุญุตู ุชููุงุฆููุง ูุจู ุฃู ููุฏูุฌ ูู ุงููุณุฎุฉ ุงูุฃุณุงุณูุฉ ูู ุงููุดุฑูุน.
## ๐งช ุฎุทูุงุช ุงูุชุญูู

| ุงูุฎุทูุฉ | ุงููุตู |
|--------|-------|
| Checkout repository | ุชุญููู ุงูููุฏ ูู ุงููุณุชูุฏุน ุจุงุณุชุฎุฏุงู `actions/checkout@v4` |
| Setup Node.js | ุฅุนุฏุงุฏ ุจูุฆุฉ Node.js ุจุฅุตุฏุงุฑ 18 ูุชูุนูู ุงููุงุด ููุญุฒู |
| Install dependencies | ุชุซุจูุช ุงูุญุฒู ุจุงุณุชุฎุฏุงู `npm ci` ูุถูุงู ุซุจุงุช ุงูุฅุตุฏุงุฑุงุช |
| Run lint | ุงูุชุญูู ูู ุฌูุฏุฉ ุงูููุฏ ุจุงุณุชุฎุฏุงู `npm run lint` |
| Run tests | ุชุดุบูู ุงุฎุชุจุงุฑุงุช ุงููุญุฏุฉ ุจุงุณุชุฎุฏุงู `npm test` |
| Build project | ุจูุงุก ุงููุดุฑูุน ุจุงุณุชุฎุฏุงู `npm run build` (ุงุฎุชูุงุฑู) |
| Upload test results | ุฑูุน ูุชุงุฆุฌ ุงูุงุฎุชุจุงุฑุงุช ุฅูู GitHub Artifacts (ุงุฎุชูุงุฑู) |
| Notify on failure | ุนุฑุถ ุฑุณุงูุฉ ูุดู ูู ุญุงู ุชุนุทู ุฃู ุฎุทูุฉ |
# =========================================
# Web3Pay CI Workflow Documentation
# ูุฐุง ุงูุชูููู ููุฏู ุฅูู ุถูุงู ุฌูุฏุฉ ุงูููุฏ ูุงุณุชูุฑุงุฑู ูู ูุดุฑูุน Web3Pay
# ุนุจุฑ ุชูููุฐ ุณูุณูุฉ ูู ุงููุญูุตุงุช ุงูุชููุงุฆูุฉ ุนูุฏ ูู ุชุนุฏูู ุนูู ูุฑุน `main`.
#
# ๐ Trigger:
# - push ุฅูู ูุฑุน main
# - pull request ุฅูู ูุฑุน main
#
# ๐งช ุฎุทูุงุช ุงูุชุญูู:
# - Checkout repository: ุชุญููู ุงูููุฏ
# - Setup Node.js: ุฅุนุฏุงุฏ ุจูุฆุฉ ุงูุนูู
# - Install dependencies: ุชุซุจูุช ุงูุญุฒู
# - Run lint: ุงูุชุญูู ูู ุฌูุฏุฉ ุงูููุฏ
# - Run tests: ุชุดุบูู ุงูุงุฎุชุจุงุฑุงุช
# - Build project: ุจูุงุก ุงููุดุฑูุน (ุงุฎุชูุงุฑู)
# - Upload test results: ุฑูุน ุงููุชุงุฆุฌ (ุงุฎุชูุงุฑู)
# - Notify on failure: ุฅุดุนุงุฑ ูู ุญุงู ุงููุดู
#
# ูู ุฎุทูุฉ ุชูุซู ุงูุชุฒุงู Web3Pay ุจุงูุณูุงุฏุฉ ุงูุฑูุฒูุฉ ูุฌูุฏุฉ ุงูุจูุงุก ูู ุงููุงุชู ูุจุงุดุฑุฉ.
# =========================================

name: Web3Pay CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      ...
